inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - doorkeeper/**/*
    - spec/dummy/db/*
    - spec/dummy/config/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - doorkeeper-mongodb.gemspec

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/**/*

Naming/FileName:
  Exclude:
    - lib/doorkeeper-mongodb.rb
    - gemfiles/Gemfile.*

Rails/RakeEnvironment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/WordArray:
  MinSize: 3

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  MinSize: 3

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/TrailingEmptyLines:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: leading

Layout/LineLength:
  Exclude:
    - spec/**/*
  Max: 120
