name: CI RSpec Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.ruby }}
    env:
      CI: true
      TESTOPTS: -v
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # mongoid7 requires activemodel >= 5.1, < 8.0
          - orm: 'mongoid7'
            ruby: '2.6'
            rails: '6.0'
            experimental: false
          - orm: 'mongoid7'
            ruby: '2.7'
            rails: '6.0'
            experimental: false
          - orm: 'mongoid7'
            ruby: '3.0'
            rails: '6.1'
            experimental: false
          - orm: 'mongoid7'
            ruby: '3.0'
            rails: '7.0'
            experimental: false
          - orm: 'mongoid7'
            ruby: '3.1'
            rails: '7.0'
            experimental: false

          # mongoid8 requires activemodel >= 5.1, < 8.0
          - orm: 'mongoid8'
            ruby: '2.6'
            rails: '6.0'
            experimental: false
          - orm: 'mongoid8'
            ruby: '2.7'
            rails: '6.0'
            experimental: false
          - orm: 'mongoid8'
            ruby: '3.0'
            rails: '6.1'
            experimental: false
          - orm: 'mongoid8'
            ruby: '3.0'
            rails: '7.0'
            experimental: false
          - orm: 'mongoid8'
            ruby: '3.1'
            rails: '7.0'
            experimental: false

          # jruby
          - orm: 'mongoid7'
            ruby: 'jruby'
            rails: '6.1'
            experimental: false

          - orm: 'mongoid8'
            ruby: 'jruby'
            rails: '6.1'
            experimental: false

          # truffleruby
          - orm: 'mongoid7'
            ruby: 'truffleruby'
            rails: '6.1'
            experimental: false

          # truffleruby
          - orm: 'mongoid8'
            ruby: 'truffleruby'
            rails: '6.1'
            experimental: false

          # experimental
          - orm: 'mongoid7'
            ruby: 'head'
            rails: '7.0'
            experimental: true
          - orm: 'mongoid7'
            ruby: 'jruby-head'
            rails: '7.0'
            experimental: true
          - orm: 'mongoid7'
            ruby: 'truffleruby-head'
            rails: '7.0'
            experimental: true

          # experimental
          - orm: 'mongoid8'
            ruby: 'head'
            rails: '7.0'
            experimental: true
          - orm: 'mongoid8'
            ruby: 'jruby-head'
            rails: '7.0'
            experimental: true
          - orm: 'mongoid8'
            ruby: 'truffleruby-head'
            rails: '7.0'
            experimental: true

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: start mongodb
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 4.4
          mongodb-replica-set: rs0

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2

      - name: bundle install
        run:  bundle install --jobs 4 --retry 3
        env:
          RAILS: ${{ matrix.rails }}
          BUNDLE_GEMFILE: 'gemfiles/Gemfile.${{matrix.orm}}.rb'

      - name: test
        timeout-minutes: 10
        run: bundle exec rake spec
        continue-on-error: ${{ matrix.experimental }}
        env:
          RAILS: ${{ matrix.rails }}
          BUNDLE_GEMFILE: 'gemfiles/Gemfile.${{matrix.orm}}.rb'
